"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# SECURITY WARNING: defaults to OFF. A forgotten env var must never turn debug
# on in production, so opt in explicitly with DEBUG=true for local development.
DEBUG = env_bool('DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret!
# Outside DEBUG this must come from the environment — refuse to boot otherwise
# rather than silently running on a public, source-controlled key.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'SECRET_KEY is not set. Generate one with '
            '`python -c "import secrets; print(secrets.token_urlsafe(50))"` '
            'and set it as an environment variable.'
        )
    SECRET_KEY = 'django-insecure-local-development-key-do-not-use-in-production'

# Routing/geocoding provider. Without a real key the routing layer falls back to
# canned distances, which would render fabricated HOS compliance verdicts — so a
# production boot without one is a hard error. 'MOCK' opts in deliberately.
ORS_API_KEY = os.environ.get('ORS_API_KEY')
if not ORS_API_KEY and not DEBUG and not env_bool('ALLOW_MOCK_ROUTING', False):
    raise ImproperlyConfigured(
        'ORS_API_KEY is not set. Without it the app returns mock distances and '
        'would present invented compliance results as real. Set a key from '
        'https://openrouteservice.org/dev/#/signup, or set ALLOW_MOCK_ROUTING=true '
        'to acknowledge the risk (non-production only).'
    )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "accounts",
    "trips",
    "routing",
    "hos",
    "logs",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # Serves admin/DRF static files in production without a separate web server.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Blunt abuse limits: credential stuffing and signup spam are the realistic
    # attacks against an unauthenticated JSON API.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('THROTTLE_ANON', '60/hour'),
        'user': os.environ.get('THROTTLE_USER', '1000/hour'),
        'auth': os.environ.get('THROTTLE_AUTH', '10/hour'),
        'trip_create': os.environ.get('THROTTLE_TRIP_CREATE', '60/hour'),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _database_from_url(url: str) -> dict:
    from urllib.parse import parse_qs, unquote, urlparse

    # psycopg2 accepts postgresql://; some hosts provide postgres://
    if url.startswith('postgres://'):
        url = 'postgresql://' + url[len('postgres://'):]

    parsed = urlparse(url)
    query = parse_qs(parsed.query)
    host = parsed.hostname or ''

    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': host,
        'PORT': str(parsed.port or 5432),
    }

    sslmode = query.get('sslmode', [None])[0]
    if sslmode or host not in {'localhost', '127.0.0.1', 'db'}:
        config['OPTIONS'] = {'sslmode': sslmode or 'require'}

    return config


def _local_database_config() -> dict:
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'eld_planner'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5434'),
    }


def _resolve_database_config() -> dict:
    database_url = os.environ.get('DATABASE_URL')
    if database_url:
        return {'default': _database_from_url(database_url)}

    pg_host = os.environ.get('PGHOST')
    if pg_host:
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('PGDATABASE', os.environ.get('POSTGRES_DB', 'eld_planner')),
                'USER': os.environ.get('PGUSER', os.environ.get('POSTGRES_USER', 'postgres')),
                'PASSWORD': os.environ.get('PGPASSWORD', os.environ.get('POSTGRES_PASSWORD', '')),
                'HOST': pg_host,
                'PORT': os.environ.get('PGPORT', os.environ.get('POSTGRES_PORT', '5432')),
            }
        }

    if not DEBUG and os.environ.get('RENDER'):
        raise RuntimeError(
            'DATABASE_URL is not set. In Render: open your PostgreSQL service, '
            'copy the Internal Database URL, add it as DATABASE_URL on the web service, '
            'or use Environment → Link Database.'
        )

    return {'default': _local_database_config()}


DATABASES = _resolve_database_config()

# Reuse connections between requests; Render's Postgres is a network hop away
# and a fresh TCP+TLS handshake per request is a meaningful cost.
for _db in DATABASES.values():
    _db.setdefault('CONN_MAX_AGE', int(os.environ.get('DB_CONN_MAX_AGE', 60)))
    _db.setdefault('CONN_HEALTH_CHECKS', True)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Security — only enforced outside DEBUG so local http development still works.

if not DEBUG:
    # Render/Vercel terminate TLS upstream, so trust their forwarded scheme.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 60 * 60 * 24 * 30))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
] or CORS_ALLOWED_ORIGINS


# Email — password reset needs a real transport in production. Without SMTP
# settings the console backend is used, which prints the link to the logs.

EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@spottertrucklogger.app')
# Where the reset link should point — the deployed frontend, not the API.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173').rstrip('/')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '{levelname} {asctime} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'},
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        # svglib logs every unsupported style attribute at DEBUG; far too noisy.
        'svglib': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}
