# Generated by Django 6.0.6 on 2026-06-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_driving_hours", models.FloatField(default=0.0)),
                ("total_on_duty_hours", models.FloatField(default=0.0)),
                ("total_off_duty_hours", models.FloatField(default=0.0)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("svg_content", models.TextField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DutyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                            ("DRIVING", "Driving"),
                            ("ON_DUTY_NOT_DRIVING", "On Duty Not Driving"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("distance_miles", models.FloatField(default=0.0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_events",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
    ]
