# Generated by Django 6.0.8 on 2026-08-06 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dutyevent",
            options={"ordering": ["start_time"]},
        ),
    ]
