# Generated by Django 5.2.7 on 2026-08-04 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_trip_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_used', models.FloatField(default=0.0)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=255)),
                ('truck_number', models.CharField(blank=True, default='', max_length=100)),
                ('distance_miles', models.FloatField(blank=True, null=True)),
                ('estimated_driving_hours', models.FloatField(blank=True, null=True)),
                ('is_compliant', models.BooleanField()),
                ('overall_score', models.FloatField()),
                ('violation_count', models.IntegerField(default=0)),
                ('reasoning_summary', models.TextField(blank=True, default='')),
                ('report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_checks', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_checks', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
